export const mockDataCloud = [
  {
    type: "folder",
    name: "Cloud",
    creation_date: "2024-02-16",
    id: 1,
    isFavorite: false,
    isTrash: false,
    owner_id: 1,
    parent_folder_id: 7,
  },
  {
    type: "folder",
    name: "Folder",
    creation_date: "2024-02-16",
    id: 2,
    isFavorite: false,
    isTrash: false,
    owner_id: 1,
    parent_folder_id: 7,
  },
  {
    type: "folder",
    name: "Folder",
    creation_date: "2024-02-16",
    id: 3,
    isFavorite: true,
    isTrash: false,
    owner_id: 1,
    parent_folder_id: 7,
  },
  {
    type: "file",
    extension: "mp3",
    name: "Audio File",
    creation_date: "2024-02-14",
    id: 4,
    isFavorite: false,
    isTrash: false,
    folder_id: 3,
    owner_id: 5,
  },
  {
    type: "file",
    extension: "png",
    name: "Image File",
    creation_date: "2024-02-14",
    id: 5,
    isFavorite: false,
    isTrash: false,
    folder_id: 3,
    owner_id: 5,
  },
  {
    type: "file",
    extension: "txt",
    name: "Text trash",
    creation_date: "2024-02-14",
    id: 6,
    isFavorite: false,
    isTrash: false,
    folder_id: 3,
    owner_id: 5,
  },
  {
    type: "folder",
    name: "Vacation Photos",
    creation_date: "2024-03-01",
    id: 7,
    isFavorite: true,
    isTrash: false,
    owner_id: 2,
    parent_folder_id: 1,
  },
  {
    type: "folder",
    name: "Work Documents",
    creation_date: "2024-02-28",
    id: 8,
    isFavorite: false,
    isTrash: false,
    owner_id: 2,
    parent_folder_id: 2,
  },
  {
    type: "file",
    extension: "docx",
    name: "Project Proposal",
    creation_date: "2024-02-28",
    id: 9,
    isFavorite: true,
    isTrash: false,
    folder_id: 8,
    owner_id: 2,
  },
  {
    type: "file",
    extension: "jpg",
    name: "Family Picnic",
    creation_date: "2024-03-02",
    id: 10,
    isFavorite: true,
    isTrash: false,
    folder_id: 7,
    owner_id: 2,
  },
  {
    type: "file",
    extension: "xlsx",
    name: "Financial Report",
    creation_date: "2024-03-01",
    id: 11,
    isFavorite: false,
    isTrash: false,
    folder_id: 8,
    owner_id: 2,
  },
  {
    type: "folder",
    name: "Unused Projects",
    creation_date: "2024-02-27",
    id: 12,
    isFavorite: false,
    isTrash: false,
    owner_id: 2,
    parent_folder_id: 1,
  },
  {
    type: "file",
    extension: "pptx",
    name: "Presentation Slides",
    creation_date: "2024-02-27",
    id: 13,
    isFavorite: false,
    isTrash: false,
    folder_id: 12,
    owner_id: 2,
  },
  {
    type: "file",
    extension: "pdf",
    name: "User Manual",
    creation_date: "2024-02-27",
    id: 14,
    isFavorite: false,
    isTrash: false,
    folder_id: 12,
    owner_id: 2,
  },
];
